from tkinter import *

def metiers():
    fenetre = Tk()
    fenetre.title("Pôle école")
    fenetre.geometry("900x670")
    fenetre.configure(bg='#9c742f')

    label = Label(fenetre, text="Les Métiers",font=("arial", 25),fg="white")
    label.config(bg="#9c742f")
    label.pack()

    zone1=Frame(fenetre, bg='#9c742f')
    zone2=Frame(fenetre, bg='#9c752f')

    label1 = Label(zone1, text="Serveur/Serveuse",font=("arial", 10),fg="white")
    label1.config(bg="#9c742f")
    label1.pack()
    label2 = Label(zone1, text="Travailler dans un restaurant ou un café.",font=("arial", 9),fg="black")
    label2.config(bg="#9c742f")
    label2.pack()

    label3 = Label(zone1, text="Barista",font=("arial", 10),fg="white")
    label3.config(bg="#9c742f")
    label3.pack()
    label4 = Label(zone1, text="Préparer et servir des boissons dans un café.",font=("arial", 9),fg="black")
    label4.config(bg="#9c742f")
    label4.pack()

    label5 = Label(zone1, text="Caissier(ère)",font=("arial", 10),fg="white")
    label5.config(bg="#9c742f")
    label5.pack()
    label6 = Label(zone1, text="Travailler dans un magasin ou une supérette.",font=("arial", 9),fg="black")
    label6.config(bg="#9c742f")
    label6.pack()

    label7 = Label(zone1, text="Baby-sitting",font=("arial", 10),fg="white")
    label7.config(bg="#9c742f")
    label7.pack()
    label8 = Label(zone1, text="Garder des enfants pendant que les parents sont absents.",font=("arial", 9),fg="black")
    label8.config(bg="#9c742f")
    label8.pack()

    label9 = Label(zone1, text="Tuteur privé",font=("arial", 10),fg="white")
    label9.config(bg="#9c742f")
    label9.pack()
    label10 = Label(zone1, text="Aider d'autres étudiants à comprendre des matières spécifiques.",font=("arial", 9),fg="black")
    label10.config(bg="#9c742f")
    label10.pack()

    label11 = Label(zone1, text="Employé(e) de bibliothèque",font=("arial", 10),fg="white")
    label11.config(bg="#9c742f")
    label11.pack()
    label12 = Label(zone1, text="Travailler dans la bibliothèque de l'université.",font=("arial", 9),fg="black")
    label12.config(bg="#9c742f")
    label12.pack()

    label13 = Label(zone1, text="Assistant(e) de recherche",font=("arial", 10),fg="white")
    label13.config(bg="#9c742f")
    label13.pack()
    label14 = Label(zone1, text="Travailler avec des professeurs sur des projets de recherche.",font=("arial", 9),fg="black")
    label14.config(bg="#9c742f")
    label14.pack()

    label15 = Label(zone1, text="Assistant(e) de recherche",font=("arial", 10),fg="white")
    label15.config(bg="#9c742f")
    label15.pack()
    label16 = Label(zone1, text="Travailler avec des professeurs sur des projets de recherche.",font=("arial", 9),fg="black")
    label16.config(bg="#9c742f")
    label16.pack()

    label17 = Label(zone1, text="Vendeur(euse) en magasin",font=("arial", 10),fg="white")
    label17.config(bg="#9c742f")
    label17.pack()
    label18 = Label(zone1, text="Travailler dans le secteur de la vente au détail.",font=("arial", 9),fg="black")
    label18.config(bg="#9c742f")
    label18.pack()

    label19 = Label(zone1, text="Réceptionniste",font=("arial", 10),fg="white")
    label19.config(bg="#9c742f")
    label19.pack()
    label20 = Label(zone1, text="Travailler à la réception d'un hôtel ou d'un bureau.",font=("arial", 9),fg="black")
    label20.config(bg="#9c742f")
    label20.pack()

    label21 = Label(zone1, text="Garde de nuit",font=("arial", 10),fg="white")
    label21.config(bg="#9c742f")
    label21.pack()
    label22 = Label(zone1, text="Surveiller les résidences étudiantes ou travailler dans la sécurité.",font=("arial", 9),fg="black")
    label22.config(bg="#9c742f")
    label22.pack()

    label23 = Label(zone1, text="Agent(e) de call center",font=("arial", 10),fg="white")
    label23.config(bg="#9c742f")
    label23.pack()
    label24 = Label(zone1, text="Répondre aux appels téléphoniques pour une entreprise.",font=("arial", 9),fg="black")
    label24.config(bg="#9c742f")
    label24.pack()

    label25 = Label(zone1, text="Livreur(se)",font=("arial", 10),fg="white")
    label25.config(bg="#9c742f")
    label25.pack()
    label26 = Label(zone1, text="Livrer des repas, des colis ou des courses à domicile.",font=("arial", 9),fg="black")
    label26.config(bg="#9c742f")
    label26.pack()

    label27 = Label(zone2, text="Agent(e) d'accueil",font=("arial", 10),fg="white")
    label27.config(bg="#9c742f")
    label27.pack()
    label28 = Label(zone2, text="Travailler lors d'événements, de conférences ou de salons.",font=("arial", 9),fg="black")
    label28.config(bg="#9c742f")
    label28.pack()

    label29 = Label(zone2, text="Agent(e) de promotion",font=("arial", 10),fg="white")
    label29.config(bg="#9c742f")
    label29.pack()
    label30 = Label(zone2, text="Distribuer des échantillons ou des flyers pour promouvoir des produits.",font=("arial", 9),fg="black")
    label30.config(bg="#9c742f")
    label30.pack()

    label31 = Label(zone2, text="Photographe freelance",font=("arial", 10),fg="white")
    label31.config(bg="#9c742f")
    label31.pack()
    label32 = Label(zone2, text="Couvrir des événements, des mariages ou proposer des séances photo.",font=("arial", 9),fg="black")
    label32.config(bg="#9c742f")
    label32.pack()

    label33 = Label(zone2, text="Assistant(e) de vente en ligne",font=("arial", 10),fg="white")
    label33.config(bg="#9c742f")
    label33.pack()
    label34 = Label(zone2, text="Gérer les ventes et le service client pour des entreprises en ligne.",font=("arial", 9),fg="black")
    label34.config(bg="#9c742f")
    label34.pack()

    label35 = Label(zone2, text="Animateur(ice)",font=("arial", 10),fg="white")
    label35.config(bg="#9c742f")
    label35.pack()
    label36 = Label(zone2, text="Travailler dans des centres de loisirs ou des camps.",font=("arial", 9),fg="black")
    label36.config(bg="#9c742f")
    label36.pack()

    label37 = Label(zone2, text="Assistant(e) personnel(le)",font=("arial", 10),fg="white")
    label37.config(bg="#9c742f")
    label37.pack()
    label38 = Label(zone2, text="Aider des particuliers dans leurs tâches quotidiennes.",font=("arial", 9),fg="black")
    label38.config(bg="#9c742f")
    label38.pack()

    label39 = Label(zone2, text="Cours particuliers en ligne",font=("arial", 10),fg="white")
    label39.config(bg="#9c742f")
    label39.pack()
    label40 = Label(zone2, text="Enseigner des matières spécifiques à d'autres étudiants via des plateformes en ligne.",font=("arial", 9),fg="black")
    label40.config(bg="#9c742f")
    label40.pack()

    label41 = Label(zone2, text="Testeur(euse) de produits",font=("arial", 10),fg="white")
    label41.config(bg="#9c742f")
    label41.pack()
    label42 = Label(zone2, text="Tester des produits pour des entreprises.",font=("arial", 9),fg="black")
    label42.config(bg="#9c742f")
    label42.pack()

    label43 = Label(zone2, text="Agent(e) de sondage",font=("arial", 10),fg="white")
    label43.config(bg="#9c742f")
    label43.pack()
    label44 = Label(zone2, text="Réaliser des sondages ou des enquêtes pour des instituts de recherche.",font=("arial", 9),fg="black")
    label44.config(bg="#9c742f")
    label44.pack()

    label45 = Label(zone2, text="Assistant(e) en événementiel",font=("arial", 10),fg="white")
    label45.config(bg="#9c742f")
    label45.pack()
    label46 = Label(zone2, text="Travailler sur l'organisation d'événements.",font=("arial", 9),fg="black")
    label46.config(bg="#9c742f")
    label46.pack()

    label47 = Label(zone2, text="Assistant(e) en marketing digital",font=("arial", 10),fg="white")
    label47.config(bg="#9c742f")
    label47.pack()
    label48 = Label(zone2, text="Aider à gérer les médias sociaux, la publicité en ligne, etc.",font=("arial", 9),fg="black")
    label48.config(bg="#9c742f")
    label48.pack()

    label49 = Label(zone2, text="Assistant(e) en informatique",font=("arial", 10),fg="white")
    label49.config(bg="#9c742f")
    label49.pack()
    label50 = Label(zone2, text="Aider d'autres étudiants ou entreprises avec des problèmes informatiques.",font=("arial", 9),fg="black")
    label50.config(bg="#9c742f")
    label50.pack()

    bouton_retour=Button(zone2, text=">>>retour",fg="white", command=fenetre.quit)
    bouton_retour.config(bg="#573f17")
    bouton_retour.pack(side='bottom')

    zone1.pack(fill=Y, padx=30,pady=60,side="left")
    zone2.pack(fill=Y, padx=30,pady=60,side="right")



    fenetre.mainloop()
metiers()
